### ISSUE TITLE
Black screen after newest update

### ISSUE THREAD

**Issue by anthonyka** [dolanmiu/MMM-awesome-alexa#118]
The Mirror will not exit anymore and is just stuck on a black screen.
Tried downgrading electron but it didn’t work

**Comment by dolanmiu** [comment]
can you show me the logs?

```
npm start dev
```

**Comment by anthonyka** [comment]
not really sure how it is supposed to work, I tried the command but got a blank white screen that said: "Devtool was disconnected from the page". if I exit, I get back to the black startup screen where I can't minimize nor exit, the Terminal is still accessible tho.

**Comment by dolanmiu** [comment]
does the terminal say anything?

**Comment by onkararj** [comment]
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "dev"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2018-07-31T10_19_46_423Z-debug.log

**Comment by drippyer** [comment]
I seem to be having this same issue after installing MMM-awesome-alexa for the first time on a previously working Mirror. What can I provide to best help you?

**Comment by dolanmiu** [comment]
Can you provide logs?

```
npm start dev
```

And the logs from the terminal

**Comment by dolanmiu** [comment]
```
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "dev"
npm ERR! node v7.10.1
npm ERR! npm v4.2.0
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! /home/pi/.npm/_logs/2018-07-31T10_19_46_423Z-debug.log
```

you are running the command in the wrong directory

**Comment by drippyer** [comment]
After cd'ing into the modules folder, the entire Mirror interface fails once the git is cloned.
The output after running `npm install dev` is as follows:

```
> magicmirror@2.5.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.5.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: calendar_monthly.
Initializing new module helper ...
Module helper loaded: MMM-MyCalendar
Initializing new module helper ...
Module helper loaded: MMM-MyWeather
Initializing new module helper ...
Module helper loaded: MMM-MyScoreboard
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: MMM-SystemStats
Initializing new module helper ...
Module helper loaded: MMM-lyft
Initializing new module helper ...
Module helper loaded: MMM-uber
Initializing new module helper ...
Module helper loaded: newsfeed
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'rxjs-compat'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: calendar_monthly.
Initializing new module helper ...
Module helper loaded: MMM-MyCalendar
Initializing new module helper ...
Module helper loaded: MMM-MyWeather
Initializing new module helper ...
Module helper loaded: MMM-MyScoreboard
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: MMM-SystemStats
Initializing new module helper ...
Module helper loaded: MMM-lyft
Initializing new module helper ...
Module helper loaded: MMM-uber
Initializing new module helper ...
Module helper loaded: newsfeed
App threw an error during load
Error: Cannot find module 'rxjs-compat'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/rxjs/Rx.js:6:10)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/rxjs/Rx.js:8:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'rxjs-compat'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/rxjs/Rx.js:6:10)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/rxjs/Rx.js:8:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
^CShutting down server...
Stopping module helper: updatenotification
Stopping module helper: MMM-MyCalendar
Stopping module helper: MMM-MyWeather
Stopping module helper: MMM-MyScoreboard
Stopping module helper: MMM-NowPlayingOnSpotify
Stopping module helper: MMM-SystemStats
Stopping module helper: MMM-lyft
Stopping module helper: MMM-uber
Stopping module helper: newsfeed
Stopping module helper: updatenotification
Stopping module helper: MMM-MyCalendar
Stopping module helper: MMM-MyWeather
Stopping module helper: MMM-MyScoreboard
Stopping module helper: MMM-NowPlayingOnSpotify
Stopping module helper: MMM-SystemStats
Stopping module helper: MMM-lyft
Stopping module helper: MMM-uber
Stopping module helper: newsfeed
```

**Comment by drippyer** [comment]
And this is the result of running `npm run electron-rebuild`

```
pi@mirrorpi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

⠋ Searching dependency treeAn unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-abi/index.js:44:9)
    at new Rebuilder (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:43:28)
    at Object.rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:217:23)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:100:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:5:58)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-05T16_01_25_918Z-debug.log
```

**Comment by drippyer** [comment]
@dolanmiu Any idea what the 'rxjs-compat' module is and why it's getting caught there?

**Comment by SamerAl-khateeb** [comment]
Hello, Can you please help me with how you can make this module work? I followed all the instructions in this [YouTube video](https://youtu.be/bWzTdv5HbVU?t=50)  to set up Amazon Developer account and set up an Alexa Device. I also went through all the steps in this [github rep](https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/docs/Installation.md)  and this [github wiki](https://github.com/dolanmiu/MMM-awesome-alexa/wiki/How-to-get-AVS-Token-2). I obtained all the codes needed (client id, secret, product id, and refresh token, etc). After I did all the steps, every time I add the config to my magic mirror configuration file the screen go black and nothing works! I tried with my credentials and without it and in both cases the result is the same. Also, I tried the config in both formats, i.e., 
{
    "module": "MMM-awesome-alexa",
    "position": "bottom_bar",
    "config": {
        "wakeWord": "Alexa",
        "clientId": "YOUR_CLIENT_ID",
        "clientSecret": "YOUR_CLIENT_SECRET",
        "deviceId": "YOUR_DEVICE_ID",
        "refreshToken": "YOUR_REFRESH_TOKEN",
        "lite": false,
        "isSpeechVisualizationEnabled": false
    }
}

and 
{
    module: "MMM-awesome-alexa",
    position: "bottom_bar",
    config: {
        wakeWord: "Alexa",
        clientId: "YOUR_CLIENT_ID",
        clientSecret: "YOUR_CLIENT_SECRET",
        deviceId: "YOUR_DEVICE_ID",
        refreshToken: "YOUR_REFRESH_TOKEN",
        lite: false,
        isSpeechVisualizationEnabled: false
    }
}

Can you help me figure out what I am doing wrong? this is so much appreciated.
