### ISSUE TITLE
error when running npm electron-rebuild

### ISSUE THREAD

**Issue by hardcore05** [dolanmiu/MMM-awesome-alexa#121]
If you know how to fix the issue, make a pull request instead.

* [ ] Before submitting your issue add logs from your MagicMirror by running command `pm2 log MagicMirror`
when i try run npm electron-rebuild in MMM-awesome-alexa folder i get errors
an unhandled error occurred inside electron-rebuild
unable to find electron-prebuilts version number, either install it or specify an explicit vrsion
please what can i do

**Comment by dolanmiu** [comment]
What is your node? try using node 8

**Comment by hardcore05** [comment]
Okay but please am new to this so how do I use node 8 for the module.
Thanks

**Comment by dolanmiu** [comment]
Try this:

http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/

**Comment by hardcore05** [comment]
Okay thank you

**Comment by hardcore05** [comment]
Okay thanks

**Comment by lodesmets** [comment]
I have the same problem: this is the error:
`Searching dependency treeAn unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/Desktop/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-abi/index.js:44:9)
    at new Rebuilder (/home/pi/Desktop/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:43:28)
    at Object.rebuild (/home/pi/Desktop/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:217:23)
    at Object.<anonymous> (/home/pi/Desktop/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:100:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/Desktop/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:5:58)
    at <anonymous>
`
