### ISSUE TITLE
problem when running npm electron rebuild

### ISSUE THREAD

**Issue by berazzi** [dolanmiu/MMM-awesome-alexa#147]
So I have had a few problems with this and started over a few times, and now again as I fear the reason I had problems was because i missed/skipped some steps during the installation.

Now I have successfully gotten to the npm electron -rebuild command, with only a few errors along the way (which I have resolved and then re run the commands that failed).

So when running it, I gets this: 

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-abi/index.js:43:9)
    at _callee6$ (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:152:37)
    at tryCatch (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:96:21)
    at Generator.tryCatcher (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:97:49)
    at /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:201:15
    at _rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:613:18)
    at rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:624:28)
    at _callee$ (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/cli.js:160:45)
    at tryCatch (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:96:21)
    at Generator.tryCatcher (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:97:49)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-04T20_10_47_558Z-debug.log

And here log file: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron-rebuild' ]
2 info using npm@5.6.0
3 info using node@v8.0.0
4 verbose run-script [ 'preelectron-rebuild',
4 verbose run-script   'electron-rebuild',
4 verbose run-script   'postelectron-rebuild' ]
5 info lifecycle mmm-awesome-alexa@1.0.0~preelectron-rebuild: mmm-awesome-alexa@1.0.0
6 info lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: mmm-awesome-alexa@1.0.0
7 verbose lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: unsafe-perm in lifecycle true
8 verbose lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: CWD: /home/pi/MagicMirror/modules/MMM-awesome-alexa
10 silly lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: Args: [ '-c', 'electron-rebuild --pre-gyp-fix' ]
11 silly lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: Returned: code: 255  signal: null
12 info lifecycle mmm-awesome-alexa@1.0.0~electron-rebuild: Failed to exec electron-rebuild script
13 verbose stack Error: mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:887:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid mmm-awesome-alexa@1.0.0
15 verbose cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa
16 verbose Linux 4.14.87-v7+
17 verbose argv "/usr/local/bin/node" "/usr/bin/npm" "run" "electron-rebuild"
18 verbose node v8.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 255
22 error mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
22 error Exit status 255
23 error Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

I looked at a few of the other issues related to this but none of it helped for me (might says that I havent tried changing node version (currently 8.0.0) as having node 8 was the only way I could get "npm install --only=prod" to work.)

Any ideas?

**Comment by tonytanjk** [comment]
Nope I got stuck with this same issue as well

**Comment by tonytanjk** [comment]
Ok I have confirmed that it works perfectly now

**Comment by tonytanjk** [comment]
But you will need to skip electron-rebuild

**Comment by tonytanjk** [comment]
But I’m wondering why I don’t get a visualizaton even though it is listening like it does not show what I say like the gif on page of intro

**Comment by berazzi** [comment]
Thanks :-) 

No luck for me though, npm install latest went fine, so did an upgrade as it stated I could upgrade from 5.6 to 6.5.
That also went fine so proceeded to installing node-abi and then it turned to shit..:

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install node-abi
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursive1.4. Extracting by manif
fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-ecd68f3b': Adgang nægtet

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ node-abi@2.5.1
added 762 packages from 473 contributors, updated 1 package and audited 12371 packages in 287.209s
found 599 vulnerabilities (558 low, 39 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm audit fix
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Invalid: lock file's @types/node@10.0.4 does not satisfy @types/node@10.0.3
npm ERR!     Missing: tslint@5.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-06T17_30_40_891Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ Npm install electron-rebuild
-bash: Npm: kommando ikke fundet
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install electron-rebuild
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursiveome/pi/MagicMirror/modul
fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-e4117cf9': Adgang nægtet

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ electron-rebuild@1.5.7
added 6 packages from 6 contributors, removed 1 package, updated 10 packages, moved 12 packages and audited 12382 packages in 153.219s
found 603 vulnerabilities (558 low, 43 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/node-abi/index.js:43:9)
    at _callee6$ (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:152:37)
    at tryCatch (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:96:21)
    at Generator.tryCatcher (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:97:49)
    at /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:201:15
    at _rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:613:18)
    at rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:624:28)
    at _callee$ (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/cli.js:160:45)
    at tryCatch (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:96:21)
    at Generator.tryCatcher (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:97:49)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-06T17_35_32_449Z-debug.log

Also, I checked regarding the "node-v57-linux-arm" but I dont have it at all...???

**Comment by tonytanjk** [comment]
Try to do sudo Su first to log into root then do the installation again as you may not have access to some of the files in node_modules

**Comment by tonytanjk** [comment]
Or you can normally install node-abi and show me what it shows?

**Comment by tonytanjk** [comment]
Yea you don’t have access to bluebird files which is what I got before I done sudo Su and doing

**Comment by tonytanjk** [comment]
May I ask how you installed it and did you install the dependencies needed?

**Comment by tonytanjk** [comment]
Like pip install pyaudio and atlas matrix library etc

**Comment by tonytanjk** [comment]
I do not have access to my pi now as I’m in school but once I get home I will check for you maybe you may be missing a few files

**Comment by tonytanjk** [comment]
And I believe you need to install all dependencies and things that dolanmiu asked users of this module to install.

**Comment by berazzi** [comment]
I did it exactly as described in the installation page, the only thing different is that it failed on pip install pyaudio so had to install a few extra things (sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools). Other than that, all is/was as described in the installation page så unless some dependencies have changed it should be good

**Comment by berazzi** [comment]
Btw, dont know if all of the mentioned was needed (libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools) but saw it on some page where some guy had the same problems, so just installed all of them rather than trying one by one.

**Comment by berazzi** [comment]
Indeed, it worked perfectly after that. Still having problems with electron though. What puzzles me is that something like this can change, im guessing it because some packages have changed since the guide was written?

**Comment by tonytanjk** [comment]
Hmm could you show me the log?

**Comment by tonytanjk** [comment]
Did you run sudo Su to gain root privileges first?Then do the commands?
Npm install npm@latest -g
Once it’s done install
Npm install node-abi
Then install
Npm install electron-rebuild

**Comment by tonytanjk** [comment]
I’m sure there should be an error in somewhere of where I stated which you may have not done sudo Su to gain root privileges so by allowing you to access restricted files

**Comment by berazzi** [comment]
Just to clarify, which log are you referring to?

I have just tried running it as root: 

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo su
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# npm install npm@latest -g
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.5.0
updated 1 package in 67.799s
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# npm install node-abi
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursiveules/MMM-awesome-alexa/n
fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-15447a60': Adgang nægtet

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ node-abi@2.5.1
updated 2 packages and audited 12382 packages in 140.421s
found 603 vulnerabilities (558 low, 43 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# npm install electron-rebuild
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursive/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.staging/string_decoder-1894c
fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-2a87e1e1': Adgang nægtet

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ electron-rebuild@1.8.2
added 15 packages from 5 contributors, removed 13 packages, updated 8 packages and audited 12197 packages in 148.59s
found 585 vulnerabilities (540 low, 43 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# 

Not much better Im afraid. But it does say several times "no access" (Adgang nægtet) which suggests a permission problems. Just weird, since its run as root.
Could I change chmod my whole mmm-aw... folder? Or would that fuck it up completely?

**Comment by tonytanjk** [comment]
Yes you could try to change the files permission to root so as to allow complete access to it

**Comment by tonytanjk** [comment]
Yea now there is an error in npm with needs resolving as you can’t change a file causing the whole installation to fail.

**Comment by tonytanjk** [comment]
Can I ask if you were able to find the v57-arm-linux file?

**Comment by berazzi** [comment]
Regarding the permission would it change anything, since im running it as root? I mean it doesnt matter, since root has access, so that wouldnt change anything?

Yea, tried running npm audit fix (as root), then i get this: 

root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# npm audit fix
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Invalid: lock file's @types/node@10.0.4 does not satisfy @types/node@10.0.3
npm ERR!     Missing: tslint@5.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-10T15_52_26_912Z-debug.log
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# npm install
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursiveules/MMM-awesome-alexa/node_modules/.staging/ms-b29eca0b (1294ms)
fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-4b4bb28c': Adgang nægtet

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 8 packages from 5 contributors, updated 2 packages and audited 12247 packages in 136.615s
found 585 vulnerabilities (540 low, 43 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# npm audit fix
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursive
fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-44b322a6': Adgang nægtet

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ request@2.88.0
+ webpack@4.28.4
added 59 packages from 27 contributors, removed 45 packages, updated 70 packages and moved 12 packages in 179.407s
fixed 105 of 585 vulnerabilities in 12247 scanned packages
  8 vulnerabilities required manual review and could not be updated
  2 package updates for 472 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
root@raspberrypi:/home/pi/MagicMirror/modules/MMM-awesome-alexa# 

It's like a neverending story of not happening.

No I did not find the file, tried running a find on the entire folder, nothing.

**Comment by tonytanjk** [comment]
No. Root as owner privileges so you would be able to access any file and I didn’t actually asked you to do npm audit fix? Did I?

**Comment by tonytanjk** [comment]
But it’s very weird that you don’t have access to the files even after root? Maybe you have to try to change permission in the file you can’t access

**Comment by tonytanjk** [comment]
Or if possible save your config.js file to a USB drive or in the raspbian OS and reinstall the whole MagicMirror there might be an error with the configs made by MichMich or with the dev Dolanmiu

**Comment by tonytanjk** [comment]
But I noticed that you could not properly install node-abi

**Comment by tonytanjk** [comment]
Could you try to manually access the file using the file manager and if it’s locked by root you can unlock it when it pops up a message saying if you want to change permissions for this file

**Comment by tonytanjk** [comment]
So sorry that I’m not a most of a help tho I tried to help but failed you. Sorry

**Comment by berazzi** [comment]
Not to worry tony I appreciate all your help. 

On the electron github page I found some answers and managed to get everything installed, had npm run electron-rebuild run without problems. So got one step further. Now I got a problem with the config.js though, but I think i messed up the syntax again so ill go over that tomorrow.

Thanks for all the help!

**Comment by tonytanjk** [comment]
Ok no problem I would love to help people who is determined in this type of project.
