### ISSUE TITLE
amazon icon keeps spinning with no output

### ISSUE THREAD

**Issue by bachoo786** [dolanmiu/MMM-awesome-alexa#152]
Hi 

I have installed everything correctly and think i am very close to make it work. However when I say alexa I get a spinning circle which keeps on spinning and nothing happens after. I also get no sound when you call alexa.

Here are my npm logs:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start', 'dev' ]
2 info using npm@6.7.0
3 info using node@v9.9.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5 verbose cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa
6 verbose Linux 4.14.79-v7+
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "dev"
8 verbose node v9.9.0
9 verbose npm  v6.7.0
10 error missing script: start
11 verbose exit [ 1, true ]

```

and this when I run the npm logs in the modules folder:

```
npm ERR! path /home/pi/MagicMirror/modules/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-09T18_22_40_828Z-debug.log
```
Can anyone help please? @dolanmiu?

Thanks.

**Comment by dolanmiu** [comment]
It could be related to this:

https://github.com/dolanmiu/MMM-awesome-alexa/issues/164#issuecomment-493762314

this is the solution which worked for @kackhaufen
