### ISSUE TITLE
Node.js npm errors when running config-helper

### ISSUE THREAD

**Issue by Canterrain** [dolanmiu/MMM-awesome-alexa#171]
I get this error when running config-helper. I'm definitely in the MMM-awesome-alexa folder, I followed all the instructions as found on the helper website (thanks for those), and npm/node.js are up to date (as is the raspberry pi). Not sure what to do.

```
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run config-helper

> mmm-awesome-alexa@1.0.0 config-helper /home/pi/MagicMirror/modules/MMM-awesome-alexa
> node config-helper.js


/home/pi/MagicMirror/modules/MMM-awesome-alexa/config-helper.js:60
            );
            ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

npm ERR! Linux 4.14.39-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v6.2.1/bin/node" "/home/pi/.nvm/versions/node/v6.2.1/bin/npm" "run" "config-helper"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! mmm-awesome-alexa@1.0.0 config-helper: `node config-helper.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 config-helper script 'node config-helper.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmm-awesome-alexa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node config-helper.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmm-awesome-alexa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmm-awesome-alexa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-awesome-alexa/npm-debug.log```

Attached the npm-debug log too.
[npm-debug.log](https://github.com/dolanmiu/MMM-awesome-alexa/files/3263022/npm-debug.log)

**Comment by dolanmiu** [comment]
You used the wrong command,

type this instead:

```bash
npm run config-helper
```

Source:

![image](https://user-images.githubusercontent.com/2917613/59074333-e182f600-88c2-11e9-9360-1b44d2e882ec.png)

https://awesome-alexa.js.org/#/installation

**Comment by dolanmiu** [comment]
>  npm/node.js are up to date

I am not sure, I think you have version v6.2.1 and npm v3.9.3, which is old

**Comment by Canterrain** [comment]
Ok, apparently my attempts to update NPM and node.js looked like they succeeded, but didn't. Now they're up to date, I delete the module and did all steps again

.. and I have a new error.

```
npm run config-helper

> mmm-awesome-alexa@1.0.0 config-helper /home/pi/MagicMirror/modules/MMM-awesome-alexa
> node config-helper.js

/home/pi/MagicMirror/modules/MMM-awesome-alexa/config-helper.js:60
            );
            ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmm-awesome-alexa@1.0.0 config-helper: `node config-helper.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 config-helper script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ER
[service in park.docx](https://github.com/dolanmiu/MMM-awesome-alexa/files/3264469/service.in.park.docx)
R!     /home/pi/.npm/_logs/2019-06-07T05_00_15_515Z-debug.log
```
[npm debug2.log](https://github.com/dolanmiu/MMM-awesome-alexa/files/3264467/npm.debug2.log)

**Comment by dolanmiu** [comment]
type in node -v and npm -v, what do you see?

**Comment by Canterrain** [comment]
Ok, got it. For some reason even though I was installing the latest versions, the old versions were left in place and that was causing a conflict. NVM solved the problem.
