### ISSUE TITLE
Module not working, interfering with display of other modules

### ISSUE THREAD

**Issue by thunderdanp** [dolanmiu/MMM-awesome-alexa#175]
I'm having an issue at the prepublish step:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy $ sudo npm run prepublish
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

snowboy@1.3.1 prepublish /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
tsc --listFiles

../../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31 [key: string]: unknown;
~~~~~~~

../../../../node_modules/@types/unist/index.d.ts:40:20 - error TS2304: Cannot find name 'unknown'.

40 [key: string]: unknown;
~~~~~~~

../../../../node_modules/@types/unist/index.d.ts:97:12 - error TS2304: Cannot find name 'unknown'.

97 value: unknown;
~~~~~~~

../../../../node_modules/@types/vfile-message/index.d.ts:69:24 - error TS2304: Cannot find name 'unknown'.

69 [key: string]: unknown;
~~~~~~~

../../../../node_modules/@types/vfile/index.d.ts:48:15 - error TS2304: Cannot find name 'unknown'.

48 data: unknown;
~~~~~~~

/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/node_modules/@types/node/base.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/node_modules/@types/node/index.d.ts
/home/pi/MagicMirror/node_modules/@types/events/index.d.ts
/home/pi/MagicMirror/node_modules/@types/minimatch/index.d.ts
/home/pi/MagicMirror/node_modules/@types/glob/index.d.ts
/home/pi/MagicMirror/node_modules/@types/unist/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile-message/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile/index.d.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! snowboy@1.3.1 prepublish: tsc --listFiles
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the snowboy@1.3.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-07-16T01_35_25_659Z-debug.log
```

And here's the log:
`0 info it worked if it ends with ok 1 warn npm npm does not support Node.js v10.15.2 2 warn npm You should probably upgrade to a newer version of node as we 3 warn npm can't make any promises that npm will work with this version. 4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9. 5 warn npm You can find the latest version at https://nodejs.org/ 6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prepublish' ] 7 info using npm@5.8.0 8 info using node@v10.15.2 9 verbose run-script [ 'prepublish' ] 10 info lifecycle snowboy@1.3.1~prepublish: snowboy@1.3.1 11 verbose lifecycle snowboy@1.3.1~prepublish: unsafe-perm in lifecycle true 12 verbose lifecycle snowboy@1.3.1~prepublish: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/modules/MMM$ 13 verbose lifecycle snowboy@1.3.1~prepublish: CWD: /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy 14 silly lifecycle snowboy@1.3.1~prepublish: Args: [ '-c', 'tsc --listFiles' ] 15 silly lifecycle snowboy@1.3.1~prepublish: Returned: code: 2 signal: null 16 info lifecycle snowboy@1.3.1~prepublish: Failed to exec prepublish script 17 verbose stack Error: snowboy@1.3.1 prepublish: tsc --listFiles17 verbose stack Exit status 2 17 verbose stack at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16) 17 verbose stack at EventEmitter.emit (events.js:189:13) 17 verbose stack at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14) 17 verbose stack at ChildProcess.emit (events.js:189:13) 17 verbose stack at maybeClose (internal/child_process.js:970:16) 17 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) 18 verbose pkgid snowboy@1.3.1 19 verbose cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy 20 verbose Linux 4.19.57-v7+ 21 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "prepublish" 22 verbose node v10.15.2 23 verbose npm v5.8.0 24 error code ELIFECYCLE 25 error errno 2 26 error snowboy@1.3.1 prepublish:tsc --listFiles 26 error Exit status 2 27 error Failed at the snowboy@1.3.1 prepublish script. 27 error This is probably not a problem with npm. There is likely additional logging output above. 28 verbose exit [ 2, true ]`

Also, including the module in the MM config file messes up display of my weather module, seen here:

![image](https://user-images.githubusercontent.com/30962928/61335584-050f5980-a7fc-11e9-9ae4-90f5cde8a363.png)

The weather should be in the top_right region. Any suggestions are appreciated. Thanks!

**Comment by leyts** [comment]
I'm having the same error but with `npm install` inside `~/MagicMirror/node_modules/snowboy`. By any chance have you found a solution?

**Comment by dolanmiu** [comment]
Duplicate of:

https://github.com/dolanmiu/MMM-awesome-alexa/issues/174

**Comment by berne88** [comment]
#174 same
