### ISSUE TITLE
error trying to install

### ISSUE THREAD

**Issue by berne88** [dolanmiu/MMM-awesome-alexa#176]
If you know how to fix the issue, make a pull request instead.

* [ ] Before submitting your issue add logs from your MagicMirror by running command `pm2 log MagicMirror`
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm install --only=prod 

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v72-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@12.7.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v72-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@12.7.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'nan'
Require stack:
- /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)
    at Object.runInThisContext (vm.js:316:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at evalScript (internal/process/execution.js:80:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'nan'
Require stack:
- /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)
    at Object.runInThisContext (vm.js:316:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at evalScript (internal/process/execution.js:80:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gypgyp  ERR!ERR!  configure errorconfigure error 
 
gypgyp  ERR!ERR!  stackstack Error: `gyp` failed with exit code: 1
 Error: `gyp` failed with exit code: 1
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:348:16)
     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:348:16)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:203:13)
     at ChildProcess.emit (events.js:203:13)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gypgyp  ERR!ERR!  SystemSystem Linux 4.19.57-v7+
 Linux 4.19.57-v7+
gypgyp  ERR!ERR!  commandcommand "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm"
 "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm"
gypgyp  ERR!ERR!  cwdcwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
 /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gypgyp  ERR!ERR!  node -vnode -v v12.7.0
 v12.7.0
gypgyp  ERR!ERR!  node-gyp -vnode-gyp -v v3.8.0
 v3.8.0
gypgyp  ERR!ERR!  not oknot ok 
 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.19.57-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
node-pre-gyp ERR! node -v v12.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v72-linux-arm' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-08-11T17_41_52_541Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $

**Comment by zp1der** [comment]
You have to downgrade your node version to version 8.x.x. Search around on Google on how to do so. Anyways I wouldn’t carry on with this module because of all the current issues going on with it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
