### ISSUE TITLE
Error when using Jarvis Hotword

### ISSUE THREAD

**Issue by Snorzze** [dolanmiu/MMM-awesome-alexa#185]
Hey,

when I try to use the Hotword "Jarvis" I get the following exception: 

```
[17:06:52.540] [ERROR]  Error: Loaded hotwords count does not match number of hotwords defined.
    at new SnowboyDetect (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:66:19)
    at new t.HotwordDetector (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:2186)
    at t.IdleState.onEnter (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:2957)
    at new t.AlexaStateMachine (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:4674)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:9139)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

I tested it also with the Hotwords "Alexa" and "Snowboy" and it works just find. Looks like just "Jarvis" has a Problem with me. Any ideas or suggestions?

Thanks!

**Comment by dolanmiu** [comment]
Might be related to this:

https://github.com/Kitt-AI/snowboy/issues/447
