### ISSUE TITLE
No response from Awesome Alexa module

### ISSUE THREAD

**Issue by ssoulages** [dolanmiu/MMM-awesome-alexa#186]
Background: I was able to generate the refresh token. My Config.js is updated accordingly. The MM works fine outside of Alexa. I can use arecord and aplay to successfully test my mic and speakers. But despite all this, the Alexa app is not responding at all. 

Seeing this in the console: 
[11:20:28.835] [ERROR]  (node:32390) UnhandledPromiseRejectionWarning: Error: [object Object]
    at obtainToken.then.catch.e (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:6228)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[11:20:28.840] [ERROR]  (node:32390) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[11:20:28.842] [ERROR]  (node:32390) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andyb2000** [comment]
I get that error if the clientId and clientSecret are incorrect, so I'd go through those steps again to regenerate them.
