### ISSUE TITLE
Cannot find module snowboy.node

### ISSUE THREAD

**Issue by ezar** [dolanmiu/MMM-awesome-alexa#19]
0|MagicMir | App threw an error during load
0|MagicMir | Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.7-linux-arm/snowboy.node'
0|MagicMir |     at Module._resolveFilename (module.js:470:15)
0|MagicMir |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|MagicMir |     at Function.Module._load (module.js:418:25)
0|MagicMir |     at Module.require (module.js:498:17)
0|MagicMir |     at require (internal/module.js:20:19)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
0|MagicMir |     at Module._compile (module.js:571:32)
0|MagicMir |     at Object.Module._extensions..js (module.js:580:10)
0|MagicMir |     at Module.load (module.js:488:32)
0|MagicMir | Whoops! There was an uncaught exception...
0|MagicMir | { Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.7-linux-arm/snowboy.node'
0|MagicMir |     at Module._resolveFilename (module.js:470:15)
0|MagicMir |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|MagicMir |     at Function.Module._load (module.js:418:25)
0|MagicMir |     at Module.require (module.js:498:17)
0|MagicMir |     at require (internal/module.js:20:19)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
0|MagicMir |     at Module._compile (module.js:571:32)
0|MagicMir |     at Object.Module._extensions..js (module.js:580:10)
0|MagicMir |     at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }

**Comment by ezar** [comment]
npm run electron-rebuild
