### ISSUE TITLE
Problem in getting refresh token

### ISSUE THREAD

**Issue by Cihangir7000** [dolanmiu/MMM-awesome-alexa#194]
I have followed the instructions to the letter, until I come to Step 3. Configuring the Module. 
Here I experience that no matter what I do, I don't get the refresh token to work. 
With this incomplete  setup I start the MM I say the wake word "Alexa" the I get the halo and then I ask what time is it ? I can only see a white dot appear and its stays that's it. 
For that reason I have contacted Amazon first to hear there side, here is the response :- 
> 
Hello,

The steps described on the page (https://awesome-alexa.js.org/#/installation?id=step-3-configuring-the-module) are specific to the Magic Mirror implementation. We have no visibility how the link is getting generated and therefore cannot provide much guidance for it.

For instance, it is not clear why your redirect URI is https://192.168.1.74:5050/authresponse. In the example presented in the official AVS documentation (https://developer.amazon.com/en-GB/docs/alexa/alexa-voice-service/authorize-companion-site.html#lwa), the redirect URI is set to https://localhost

Again, it is not known to me how the link is being generated and I strongly suggest you reach out to the Magic Mirror support channel.

If you have any further questions about this issue, please do not reply to this email. To respond to us again about this issue, please use the following link:
https://developer.amazon.com/help/contact-us.html?caseID=6979636421
 
To contact us about a separate issue, please open a new case:
https://developer.amazon.com/public/support/contact/contact-us?subjectCategory=ALEXA
 
Do you think this resolved your issue? 

If yes, please click here:
http://www.amazon.com/gp/help/survey?p=A2LUKYQU6KPH2H&k=hy

If no, please click here:
http://www.amazon.com/gp/help/survey?p=A2LUKYQU6KPH2H&k=hn

Best regards, 

Bernardo B. 
Amazon Developer Support 
================================ 

Please do not reply to this email. To respond to us again about this issue, please use the following link: 
https://developer.amazon.com/alexa/console/contact-us/case?caseID=6979636421

To contact us about a separate issue, please open a new case: 
https://developer.amazon.com/alexa/console/contact-us

================================ 
 
Here are the logs from my Magic Mirror. 

pi@raspberrypi:~ $ pm2 log mm
[TAILING] Tailing last 15 lines for [mm] process (change the value with --lines option)
/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       | [2020-05-02 10:07:31.871] [ERROR]  (node:1191) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
0|mm       | [2020-05-02 10:07:31.873] [ERROR]  (node:1191) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
0|mm       | [2020-05-02 10:07:31.894] [ERROR]  (node:1191) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       | [2020-05-02 10:07:31.895] [ERROR]  (node:1191) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       |     at /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:6073
0|mm       |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
0|mm       | [2020-05-02 10:07:32.854] [ERROR]  (node:1191) UnhandledPromiseRejectionWarning: Error: [object Object]
0|mm       |     at /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:6073
0|mm       |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
0|mm       | [2020-05-02 10:07:32.858] [ERROR]  (node:1191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|mm       | [2020-05-02 10:07:32.859] [ERROR]  (node:1191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|mm       | [2020-05-02 10:07:32.865] [ERROR]  (node:1191) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
0|mm       | [2020-05-02 10:07:32.866] [ERROR]  (node:1191) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Expired at: 10:07:31 now is: 10:07:32

**Comment by Cihangir7000** [comment]
At the end the error was that I was pasting the whole web address with the token. I just had to copy it out and separate it.
