### ISSUE TITLE
Alexa not responding

### ISSUE THREAD

**Issue by MrWeaverZ** [dolanmiu/MMM-awesome-alexa#200]
Hi All
I am wondering if anybody would be able to help. I built a MagicMirror for my 10yrs old, I was able to install everything successfully. My only problem is with Awesome Alexa. I am 100% NOOB in this field.

I registered an Amazon  dev account, installed Alexa and configured the module. 
When  MagicMirror starts, everything loads up as it meant to except Alexa. All the other modules are running w/o issue. When I shutdown npm I can see the following errors. I tried to google it, however i did not find this error related to this module. There are articles on the net, but unfortunately I just could not find something would help me.
Thanks in advance!!

[2020-06-16 21:33:49.801] [ERROR]  (node:14896) UnhandledPromiseRejectionWarning: Error: [object Object]
    at /home/pi/MagicMirror/modules/default/MMM-awesome-alexa/node_helper.js:1:6073
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

[2020-06-16 21:33:49.804] [ERROR]  (node:14896) UnhandledPromiseRejectionWarning: Error: [object Object]
    at /home/pi/MagicMirror/modules/default/MMM-awesome-alexa/node_helper.js:1:6073
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

[2020-06-16 21:33:49.806] [ERROR]  (node:14896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

[2020-06-16 21:33:49.807] [ERROR]  (node:14896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-06-16 21:33:49.808] [ERROR]  (node:14896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-06-16 21:33:49.809] [ERROR]  (node:14896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ghost** [comment]
any solution?

**Comment by MrWeaverZ** [comment]
Hi
I did not respond any comments yet... yours is the first!
Do you have similar issue?

**Comment by ghost** [comment]
> Hi
> I did not respond any comments yet... yours is the first!
> Do you have similar issue?

yeah, I do. It's kinda weird.

**Comment by varadwattamwar** [comment]
My problem is  Alexa goes to "transiting to state: listening" then it goes on listening and then takes 4-5 min to change the state for responding.
Please someone help us out!!
