### ISSUE TITLE
MMM-awesome-alexa error after installation

### ISSUE THREAD

**Issue by drk-geek** [dolanmiu/MMM-awesome-alexa#205]
Fresh installation on RPI 3B, below error after installation, any fix, please.. 

0|mm  | [2020-07-26 01:41:26.915] [ERROR]  
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [2020-07-26 01:41:26.916] [ERROR]  
0|mm  | Error: self signed certificate
0|mm  |     at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
0|mm  |     at TLSSocket.emit (events.js:200:13)
0|mm  |     at TLSSocket._finishInit (_tls_wrap.js:792:8)
0|mm  |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
0|mm  |     at Socket.ondata (internal/js_stream_socket.js:64:22)
0|mm  |     at Socket.emit (events.js:200:13)
0|mm  |     at addChunk (_stream_readable.js:294:12)
0|mm  |     at readableAddChunk (_stream_readable.js:275:11)
0|mm  |     at Socket.Readable.push (_stream_readable.js:210:10)
0|mm  |     at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
0|mm  |   code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
0|mm  |   source: 'socket'
0|mm  | }
0|mm  | [2020-07-26 01:41:26.919] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [2020-07-26 01:41:26.925] [ERROR]  
0|mm  | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
If you know how to fix the issue, make a pull request instead.

* [ ] Before submitting your issue add logs from your MagicMirror by running command `pm2 log MagicMirror`

**Comment by drk-geek** [comment]
posted by mistake, its an error of email module
