### ISSUE TITLE
When alexa is added to the config file whole Magic Mirror does not load, black screen

### ISSUE THREAD

**Issue by jeremyleizmagicmirror** [dolanmiu/MMM-awesome-alexa#213]
First I would like to appoligize, I am very new to coding and have next to no idea what I am doing. Thank you for any help you can provide. Whenever the Awesome-Alexa config is put in the MagicMirror config file, I get a black screen and the Magic Mirror Module does not load at all. Here is the error message when I run npm start on the Magic Mirror file:
  at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js',
    '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[2020-11-09 13:42:58.922] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-11-09 13:42:58.923] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

I had seen on other problems you requesting to see the npm start dev response and this is what happened:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', 'dev' ]
2 info using npm@6.14.8
3 info using node@v10.23.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa
6 verbose Linux 5.4.72-v7+
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "dev"
8 verbose node v10.23.0
9 verbose npm  v6.14.8
10 error missing script: start
11 verbose exit [ 1, true ]

Thank you so much for your help, I really appreciate it!!!!
-Jeremy

**Comment by SvenHerr** [comment]
could you add your config.js file

**Comment by jimfish007** [comment]
I have the same issue and have been struggling to find a solution. I've tried multiple things and almost ready to pack it in.
