### ISSUE TITLE
Module won't load

### ISSUE THREAD

**Issue by Bl4CkGuuN** [dolanmiu/MMM-awesome-alexa#216]
The module is not loading.

Any ideas?

```
0|mm  | Checking git for module: MMM-awesome-alexa
0|mm  | [23.01.2021 20:09.49.844] [ERROR]
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [23.01.2021 20:09.49.861] [ERROR]
0|mm  | Error: spawn rec ENOENT
0|mm  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
0|mm  |     at onErrorNT (internal/child_process.js:456:16)
0|mm  |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
0|mm  |   errno: 'ENOENT',
0|mm  |   code: 'ENOENT',
0|mm  |   syscall: 'spawn rec',
0|mm  |   path: 'rec',
0|mm  |   spawnargs: [
0|mm  |     '-q',             '-r',
0|mm  |     16000,            '-c',
0|mm  |     '1',              '-e',
0|mm  |     'signed-integer', '-b',
0|mm  |     '16',             '-t',
0|mm  |     'wav',            '-',
0|mm  |     'silence',        '1',
0|mm  |     '0.1',            '0%',
0|mm  |     '1',              '1.0',
0|mm  |     '0%'
0|mm  |   ]
0|mm  | }

```

**Comment by b-nugent** [comment]
I have this problem as well, not sure what's causing it. 🤔
