### ISSUE TITLE
npm install --only=prod broken links?

### ISSUE THREAD

**Issue by Noah-Phense** [dolanmiu/MMM-awesome-alexa#217]
mirror@MirrorMirror:~/MagicMirror/modules/MMM-awesome-alexa$ npm install --only=prod
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@4.2.1: this library is no longer supported

> snowboy@1.3.1 install /home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gypgyp  ERR!ERR!  configure errorconfigure error

gypgyp  ERR!ERR!  stackstack Error: `gyp` failed with exit code: 1
 Error: `gyp` failed with exit code: 1
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:198:13)
     at ChildProcess.emit (events.js:198:13)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gypgyp  ERR!ERR! System  Linux 5.8.0-41-generic
System Linux 5.8.0-41-generic
gyp gyp ERR! ERR!command  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64"
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64"
gyp gypERR!  ERR!cwd  /home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
cwdgyp /home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
 gypERR!  node -vERR! v10.16.0
 node -vgyp v10.16.0
 ERR!gyp  node-gyp -vERR! v3.8.0
 gypnode-gyp -v  v3.8.0
ERR!gyp not ok
ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.8.0-41-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/mirror/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mirror/.npm/_logs/2021-01-30T22_12_15_413Z-debug.log

**Comment by apocalipse9** [comment]
Same problem here...

**Comment by SvenHerr** [comment]
same here

**Comment by dragonempire96** [comment]
problem still exist

**Comment by Themaster312** [comment]
Same

**Comment by Kevinjconnorsjr** [comment]
I literally just reinstalled from the beginning and it worked.

I did try using the "npm install --only=prod" a bunch of times and it never installed correctly. and then randomly i tried it from the beginning and it worked 🤷‍♂️

**Comment by joelis10** [comment]
I've got this too, anyone got a fix?

**Comment by lodionan** [comment]
Maybe the my comments in the following issue can help you guys

https://github.com/dolanmiu/MMM-awesome-alexa/issues/231
