### ISSUE TITLE
errors with npm run electron-rebuild

### ISSUE THREAD

**Issue by chaosjester** [dolanmiu/MMM-awesome-alexa#91]
Hi, trying to run npm run electron-rebuild but am having some issues.

Does anyone have any suggestions?

TIA

Output of command here:

````
pi@raspberrypi  ~/MagicMirror/modules/MMM-awesome-alexa   master  npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:130: recipe for target 'Release/obj.target/snowboy.node' failed
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
make: *** [Release/obj.target/snowboy.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.14.27-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-gyp" "rebuild" "--target=1.4.15" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.4-linux-arm" "--remote_path=./snowboy/v1.2.0/Release/" "--package_name=snowboy-v1.2.0-electron-v1.4-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: make: Entering directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:130: recipe for target 'Release/obj.target/snowboy.node' failed
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
make: *** [Release/obj.target/snowboy.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.14.27-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-gyp" "rebuild" "--target=1.4.15" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.4-linux-arm" "--remote_path=./snowboy/v1.2.0/Release/" "--package_name=snowboy-v1.2.0-electron-v1.4-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:198:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:129:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:103:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:129:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:103:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:248:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:188:27)

npm ERR! Linux 4.14.27-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "electron-rebuild"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script 'electron-rebuild --pre-gyp-fix'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmm-awesome-alexa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild --pre-gyp-fix
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmm-awesome-alexa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmm-awesome-alexa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-awesome-alexa/npm-debug.log
```

**Comment by E3V3A** [comment]
Your node and npm are outdated!
Should be at least:
```bash
# node -v && npm -v
v9.8.0
5.7.1
```

**Comment by chaosjester** [comment]
I have updated node and npm and still am still having the same issue

```
 pi@raspberrypi  ~/MagicMirror/modules/MMM-awesome-alexa   master  node -v && npm -v
v9.9.0
5.8.0
 pi@raspberrypi  ~/MagicMirror/modules/MMM-awesome-alexa   master  npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:130: recipe for target 'Release/obj.target/snowboy.node' failed
make: *** [Release/obj.target/snowboy.node] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.27-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v9.9.0/bin/node" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-gyp" "rebuild" "--target=1.4.15" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.4-linux-arm" "--remote_path=./snowboy/v1.2.0/Release/" "--package_name=snowboy-v1.2.0-electron-v1.4-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: make: Entering directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:130: recipe for target 'Release/obj.target/snowboy.node' failed
make: *** [Release/obj.target/snowboy.node] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.27-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v9.9.0/bin/node" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-gyp" "rebuild" "--target=1.4.15" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.4-linux-arm" "--remote_path=./snowboy/v1.2.0/Release/" "--package_name=snowboy-v1.2.0-electron-v1.4-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:198:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:129:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:103:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:129:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:103:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:248:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:188:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-03-24T12_49_50_834Z-debug.log
```

**Comment by dolanmiu** [comment]
You dont have `lcblas`, which is `libatlas`:

The readme told you to install lib atlas, so its strange it doesnt work if you installed it already.

Anyway, try doing this:

```
sudo apt-get install libmagic-dev libatlas-base-dev
```

**Comment by justjim1220** [comment]
Try:
npm run --electron-rebuuld

Looks like you're missing the -- in the command.

**Comment by justjim1220** [comment]
npm run --electron-rebuild

(misspelling in last post)

Apologies!

**Comment by henrikra** [comment]
Try with node v6. Magic mirror officially supports that. I am using that version and this works

**Comment by justjim1220** [comment]
I'm running the latest updated version and only time I got errors like that is when I forgot to put in the -- in the command.

**Comment by chaosjester** [comment]
> You dont have lcblas, which is libatlas:
> 
> The readme told you to install lib atlas, so its strange it doesnt work if you installed it already.
> 
> Anyway, try doing this:
> 
> sudo apt-get install libmagic-dev libatlas-base-dev

Ah whoops, must have missed that step, sorry. that has worked, please close.
